# Generated by Django 3.0.7 on 2022-05-08 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arquivo',
            name='url',
        ),
    ]
