# Generated by Django 3.2.16 on 2023-01-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloconotascriptografada',
            name='e_cipher',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bloconotascriptografada',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bloconotascriptografada',
            name='titulo',
            field=models.TextField(),
        ),
    ]
