# Generated by Django 3.2.16 on 2023-01-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230108_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloconotascriptografada',
            name='e_cipher',
            field=models.BinaryField(),
        ),
        migrations.AlterField(
            model_name='bloconotascriptografada',
            name='texto',
            field=models.BinaryField(),
        ),
    ]
